### ISSUE TITLE
naturalslopeslib external dependency causes installation problems

### ISSUE THREAD

**Issue by Warr1024** [jeremyshannon/Exile#11]
As of v0.3.0 as distributed on Minetest ContentDB, this game requires the `naturalslopeslib` dependency, but does not include it.  Failing to install it causes a broken game (terrain does not generate).  This problem has been reported by multiple users on IRC/Discord and they need to be told to install the dependency manually each time to resolve this.

Normally a Game for Minetest should be self-sufficient and include everything necessary to bootstrap the basic experience without any additional mods.  There is apparently a weird exception where a mod within a game is allowed to have a *hard dependency* and if that dependency fails then *that mod just doesn't load*, to allow games to have effectively *optional* dependencies.  However, this is probably mainly just an obscure footgun for game developers.  Minetest's Content Browser clearly does not automatically install the external dependency and can't be relied on for help here at this time.

The sanest way to resolve this is probably to just include `naturalslopeslib` directly in the game distribution.  I haven't been able to find a working git repo for it to use as a submodule, but maybe unzipping the CDB download directly into Exile's mods dir makes the most sense.  The mod is licensed as "LGPLv2.1 or later" (https://forum.minetest.net/viewtopic.php?t=18140) so it should be fine to include in an LGPLv3 game (IANAL).

**Comment by rollerozxa** [comment]
ContentDB actually downloads the `naturalslopeslib` mod along with Exile, at least for me, but it's still a bad idea since currently the user themselves need to manually enable the mod before starting a new world. I made a PR (#12) that adds `naturalslopeslib` as a git submodule from the upstream repository (https://files.creativekara.fr/git/naturalslopeslib.git) and hopefully removes it as an external dependency (removing it from `game.conf`).

**Comment by jeremyshannon** [comment]
Wow, that is a serious bug in Minetest's contentdb handling. Well, I know better than to wait for Minetest to get fixed

**Comment by Warr1024** [comment]
Yeah, I was wrong about the installation.  I think Minetest does automatically install dependencies, but it doesn't automatically activate them.  ContentDB already does a lot to detect and prevent publishing broken packages, but this is a corner case and apparently correct handling is disputed, so it will probably be the responsibility of package authors to ensure their packages actually work as distributed.  It's pretty much the same as the way they are responsible for the consequences of undeclared dependencies already.

**Comment by jeremyshannon** [comment]
>correct handling is disputed
Isn't it always? That's gotta be Minetest's #1 problem with getting PRs moved through, there's always some people arguing endlessly, and nobody in charge who can just say "okay, that's enough" and pull the switch one way or the other.
       I'd be curious to read the discussion, though, because I'm hard pressed to imagine any case where MT should automatically download the hard "game-will-crash-without-it" dependency from CDB, but then have it need to be manually activated to avoid the fail state.

 Anyways, I was about to close this as I've made the new releases with the above patch, but now it turns out ContentDB apparently doesn't like git submodules, and is choking on the merged versions. I guess I'll have to bug the contendb folks and see what they think should be done.

**Comment by Warr1024** [comment]
In order to use a repo as a submodule it needs to be accessible by everyone, everywhere, all the time.  I don't know if this is specifically what's blocking CDB, but I get an HTTP 403 error trying to access it myself.  You would probably be better off either cloning the repo onto GitHub and referencing the mirror instead, or just baking the files right into the game.

**Comment by jeremyshannon** [comment]
That's because it's a git repo, not a web page. A git clone of the same url will download the files just fine. I wonder it the contentdb guys just assumed all git repos would be like github, which will detect you coming in on port 80 and serve a webpage instead. 'Cause that's not true.

**Comment by rubenwardy** [comment]
So, here's the current state:

* ContentDB (the backend) allows games to have dependencies and handles them perfectly fine.
* Minetest won't enable hard dependencies for games automatically, resulting in mods being disabled silently.
* The dependency resolver in the Minetest client currently requires an existing base game when installing dependencies. This doesn't make sense when installing a game, because the game you're installing should be the base game. Doing this properly would require installing the game then checking the dependencies, which would be painful to make the UI for, or some other code

> correct handling is disputed

ContentDB used to reject games that had hard dependencies. This was complained about, so this requirement was dropped. It's been argued that this requirement should be readded

**Comment by rubenwardy** [comment]
Fixed this bug. There appears to be a bug in the Python Git library's submodule API, so I have changed ContentDB to run the `git submodule update --init` explicitly

https://github.com/minetest/contentdb/commit/72a95ecfcaddf6538db4742ede0dd575e2cd88e6

**Comment by jeremyshannon** [comment]
Okay, that seems to fix it, and everything's in working order. I feel like the documentation on all this could be more clear, and the current state of the "hard dependency" option is a half-measure that leaves it in a state of pointlessness. But at least now it works! Closing this issue.
